/*
 This file is part of the OdinMS Maple Story Server
 Copyright (C) 2008 Patrick Huy <patrick.huy@frz.cc>
 Matthias Butz <matze@odinms.de>
 Jan Christian Meyer <vimes@odinms.de>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation version 3 as published by
 the Free Software Foundation. You may not use, modify or distribute
 this program under any other version of the GNU Affero General Public
 License.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.opcodes;

public enum SendOpcode {

    LOGIN_STATUS(0x00), //TODO
    GUEST_ID_LOGIN(0x01), //TODO
    ACCOUNT_INFO(0x02),//I guess this was in v83 too :) //TODO
    SERVERSTATUS(0x03),//CHECK_USER_LIMIT_RESULT //TODO
    GENDER_DONE(0x04),//SET_ACCOUNT_RESULT //TODO (do we need this???)
    CONFIRM_EULA_RESULT(0x05), //TODO (do we need this???)
    CHECK_PINCODE(0x06), //TODO we have no pins
    UPDATE_PINCODE(0x07), //TODO
    
    VIEW_ALL_CHAR(0x08), //TODO
    SELECT_CHARACTER_BY_VAC(0x09), //TODO
    
    SERVERLIST(0x0A), //TODO (WORLDINFORMATION in v92)
    CHARLIST(0x0B), //TODO
    SERVER_IP(0x0C), //TODO
    CHAR_NAME_RESPONSE(0x0D), //TODO (checkduplicatedidresult)
    ADD_NEW_CHAR_ENTRY(0x0E), //TODO
    DELETE_CHAR_RESPONSE(0x0F), //TODO
    CHANGE_CHANNEL(0x10), //TODO
    PING(0x11), //TODO
    KOREAN_INTERNET_CAFE_SHIT(0x12),//Useless ignore it.
    CHANNEL_SELECTED(0x14), //TODO
    HACKSHIELD_REQUEST(0x15),//maybe this is RELOG_RESPONSE, can't care less
    RELOG_RESPONSE(0x16), //TODO
    CHECK_CRC_RESULT(0x19), //TODO
    LAST_CONNECTED_WORLD(0x1A), //TODO
    RECOMMENDED_WORLD_MESSAGE(0x1B), //TODO yea we should not have this either
    CHECK_SPW_RESULT(0x1C), //TODO
    
    /*CWvsContext::OnPacket*/
    INVENTORY_OPERATION(0x1D), //TODO
    INVENTORY_GROW(0x1E), //TODO
    STAT_CHANGED(0x1F), //TODO
    GIVE_BUFF(0x20), //TODO
    CANCEL_BUFF(0x21), //TODO
    FORCED_STAT_SET(0x22), //TODO
    FORCED_STAT_RESET(0x23), //TODO
    UPDATE_SKILLS(0x24), //TODO
    SKILL_USE_RESULT(0x25), //TODO
    FAME_RESPONSE(0x26), //TODO
    SHOW_STATUS_INFO(0x27), //TODO
    OPEN_FULL_CLIENT_DOWNLOAD_LINK(0x28), //TODO no we don't need this lmao
    MEMO_RESULT(0x29), //TODO
    MAP_TRANSFER_RESULT(0x2A), //TODO
    WEDDING_PHOTO(0x2B), //ANTI_MACRO_RESULT(0x2B), TODO need to handle ANTI_MACRO but maybe we use different macro checkers
    CLAIM_RESULT(0x2D), //TODO
    CLAIM_AVAILABLE_TIME(0x2E), //TODO
    CLAIM_STATUS_CHANGED(0x2F), //TODO
    SET_TAMING_MOB_INFO(0x30), //TODO
    QUEST_CLEAR(0x31), //TODO
    ENTRUSTED_SHOP_CHECK_RESULT(0x32), //TODO
    SKILL_LEARN_ITEM_RESULT(0x33), //TODO
    GATHER_ITEM_RESULT(0x34), //TODO
    SORT_ITEM_RESULT(0x35), //TODO
    SUE_CHARACTER_RESULT(0x37), //TODO
    TRADE_MONEY_LIMIT(0x39), //TODO
    SET_GENDER(0x3A), //TODO
    GUILD_BBS_PACKET(0x3B), //TODO
    CHAR_INFO(0x3D), //TODO
    PARTY_OPERATION(0x3E), //TODO
    BUDDYLIST(0x3F), //TODO
    GUILD_OPERATION(0x41), //TODO
    ALLIANCE_OPERATION(0x42), //TODO
    SPAWN_PORTAL(0x43), //TODO
    SERVERMESSAGE(0x44), //TODO
    INCUBATOR_RESULT(0x45), //TODO
    SHOP_SCANNER_RESULT(0x46), //TODO
    SHOP_LINK_RESULT(0x47), //TODO
    
    MARRIAGE_REQUEST(0x48), //TODO
    MARRIAGE_RESULT(0x49), //TODO
    WEDDING_GIFT_RESULT(0x4A), //TODO
    NOTIFY_MARRIED_PARTNER_MAP_TRANSFER(0x4B), //TODO
    
    CASH_PET_FOOD_RESULT(0x4C), //TODO
    SET_WEEK_EVENT_MESSAGE(0x4D), //TODO
    SET_POTION_DISCOUNT_RATE(0x4E), //TODO wtf
    
    BRIDLE_MOB_CATCH_FAIL(0x4F), //TODO
    IMITATED_NPC_RESULT(0x50), //TODO
    IMITATED_NPC_DATA(0x51), //TODO
    LIMITED_NPC_DISABLE_INFO(0x52), //TODO
    MONSTER_BOOK_SET_CARD(0x53), //TODO
    MONSTER_BOOK_SET_COVER(0x54), //TODO
    HOUR_CHANGED(0x55), //TODO
    MINIMAP_ON_OFF(0x56), //TODO
    CONSULT_AUTHKEY_UPDATE(0x57), //TODO
    CLASS_COMPETITION_AUTHKEY_UPDATE(0x58), //TODO
    WEB_BOARD_AUTHKEY_UPDATE(0x59), //TODO
    SESSION_VALUE(0x5A), //TODO
    PARTY_VALUE(0x5B), //TODO
    FIELD_SET_VARIABLE(0x5C), //TODO
    BONUS_EXP_CHANGED(0x5D),//pendant of spirit etc (guess, not sure about the opcode in v83) TODO wtf
    
    FAMILY_CHART_RESULT(0x5E), //TODO can we just delete families?
    FAMILY_INFO_RESULT(0x5F), //TODO
    FAMILY_RESULT(0x60), //TODO
    FAMILY_JOIN_REQUEST(0x61), //TODO
    FAMILY_JOIN_REQUEST_RESULT(0x62), //TODO
    FAMILY_JOIN_ACCEPTED(0x63), //TODO
    FAMILY_PRIVILEGE_LIST(0x64), //TODO
    FAMILY_FAMOUS_POINT_INC_RESULT(0x65), //TODO
    FAMILY_NOTIFY_LOGIN_OR_LOGOUT(0x66), //? is logged in. LOLWUT TODO idk
    FAMILY_SET_PRIVILEGE(0x67), //TODO
    FAMILY_SUMMON_REQUEST(0x68), //TODO
    
    NOTIFY_LEVELUP(0x69), //TODO
    NOTIFY_MARRIAGE(0x6A), //TODO
    NOTIFY_JOB_CHANGE(0x6B), //TODO
    //SET_BUY_EQUIP_EXT(0x6C),  //probably extra pendant slot for other versions?
    MAPLE_TV_USE_RES(0x6D), //It's not blank, It's a popup nibs TODO this is useless
    AVATAR_MEGAPHONE_RESULT(0x6E),//bot useless.. TODO maybe this is for megaphones?
    SET_AVATAR_MEGAPHONE(0x6F), //TODO
    CLEAR_AVATAR_MEGAPHONE(0x70), //TODO
    CANCEL_NAME_CHANGE_RESULT(0x71), //TODO
    CANCEL_TRANSFER_WORLD_RESULT(0x72), //TODO this won't ever be used
    DESTROY_SHOP_RESULT(0x73), //TODO
    FAKE_GM_NOTICE(0x74),//bad asses //TODO wtf
    SUCCESS_IN_USE_GACHAPON_BOX(0x75), //TODO
    NEW_YEAR_CARD_RES(0x76), //TODO
    RANDOM_MORPH_RES(0x77), //TODO
    CANCEL_NAME_CHANGE_BY_OTHER(0x78), //TODO
    SET_EXTRA_PENDANT_SLOT(0x79), //TODO I think this is for some cash shop thing?
    SCRIPT_PROGRESS_MESSAGE(0x7A), //TODO
    DATA_CRC_CHECK_FAILED(0x7B), //TODO
    MACRO_SYS_DATA_INIT(0x7C), //TODO
    
    /*CStage::OnPacket*/
    SET_FIELD(0x7D), //TODO
    SET_ITC(0x7E), //TODO
    SET_CASH_SHOP(0x7F), //TODO
    
    /*CField::OnPacket*/
    SET_BACK_EFFECT(0x80), //TODO
    SET_MAP_OBJECT_VISIBLE(0x81),//CMapLoadable::OnSetMapObjectVisible O_O //TODO
    CLEAR_BACK_EFFECT(0x82), //TODO
    BLOCKED_MAP(0x83),//TransferFieldRequestIgnored //TODO
    BLOCKED_CHANNEL(0x84), //TODO
    FORCED_MAP_EQUIP(0x85),//FIELD_SPECIFIC_DATA //TODO
    MULTICHAT(0x86), //TODO
    WHISPER(0x87), //TODO
    SPOUSE_CHAT(0x88), //TODO
    SUMMON_ITEM_UNAVAILABLE(0x89), //You can't use it in this map //TODO
    
    FIELD_EFFECT(0x8A), //TODO
    FIELD_OBSTACLE_ONOFF(0x8B), //TODO
    FIELD_OBSTACLE_ONOFF_LIST(0x8C), //TODO
    FIELD_OBSTACLE_ALL_RESET(0x8D), //TODO
    BLOW_WEATHER(0x8E), //TODO
    PLAY_JUKEBOX(0x8F), //TODO

    ADMIN_RESULT(0x90), //TODO
    OX_QUIZ(0x91),//QUIZ //TODO
    GMEVENT_INSTRUCTIONS(0x92),//DESC TODO
    CLOCK(0x93), //TODO
    CONTI_MOVE(0x94), //TODO
    CONTI_STATE(0x95), //TODO
    SET_QUEST_CLEAR(0x96), //TODO
    SET_QUEST_TIME(0x97), //TODO
    WARN_MESSAGE(0x98), //TODO
    SET_OBJECT_STATE(0x99), //TODO
    STOP_CLOCK(0x9A), //TODO
    ARIANT_ARENA_SHOW_RESULT(0x9B), //TODO
    PYRAMID_GAUGE(0x9D), //TODO
    PYRAMID_SCORE(0x9E), //TODO
    SPAWN_PLAYER(0xA0), //TODO
    REMOVE_PLAYER_FROM_MAP(0xA1), //TODO
    CHATTEXT(0xA2), //0 TODO
    CHATTEXT1(0xA3), //1 TODO
    CHALKBOARD(0xA4), //TODO
    UPDATE_CHAR_BOX(0xA5), //TODO
    SHOW_CONSUME_EFFECT(0xA6), //TODO
    SHOW_SCROLL_EFFECT(0xA7), //TODO
    
    SPAWN_PET(0xA8), //TODO
    MOVE_PET(0xAA), //TODO
    PET_CHAT(0xAB), //TODO
    PET_NAMECHANGE(0xAC), //TODO
    PET_EXCEPTION_LIST(0xAD), //TODO
    PET_COMMAND(0xAE), //TODO
    SPAWN_SPECIAL_MAPOBJECT(0xAF), //TODO
    REMOVE_SPECIAL_MAPOBJECT(0xB0), //TODO
    MOVE_SUMMON(0xB1), //TODO
    SUMMON_ATTACK(0xB2), //TODO
    DAMAGE_SUMMON(0xB3), //TODO
    SUMMON_SKILL(0xB4), //TODO
    SPAWN_DRAGON(0xB5), //TODO
    MOVE_DRAGON(0xB6), //TODO
    REMOVE_DRAGON(0xB7), //TODO
    MOVE_PLAYER(0xB9), //TODO
    CLOSE_RANGE_ATTACK(0xBA), //TODO
    RANGED_ATTACK(0xBB), //TODO
    MAGIC_ATTACK(0xBC), //TODO
    ENERGY_ATTACK(0xBD), //TODO
    SKILL_EFFECT(0xBE), //TODO
    CANCEL_SKILL_EFFECT(0xBF), //TODO
    DAMAGE_PLAYER(0xC0), //TODO
    FACIAL_EXPRESSION(0xC1), //TODO
    SHOW_ITEM_EFFECT(0xC2), //TODO
    SHOW_CHAIR(0xC4), //TODO
    UPDATE_CHAR_LOOK(0xC5), //TODO
    SHOW_FOREIGN_EFFECT(0xC6), //TODO
    GIVE_FOREIGN_BUFF(0xC7), //TODO
    CANCEL_FOREIGN_BUFF(0xC8), //TODO
    UPDATE_PARTYMEMBER_HP(0xC9), //TODO
    GUILD_NAME_CHANGED(0xCA), //TODO
    GUILD_MARK_CHANGED(0xCB), //TODO
    THROW_GRENADE(0xCC), //TODO
    CANCEL_CHAIR(0xCD), //TODO
    SHOW_ITEM_GAIN_INCHAT(0xCE), //TODO
    DOJO_WARP_UP(0xCF), //TODO
    LUCKSACK_PASS(0xD0), //TODO
    LUCKSACK_FAIL(0xD1), //TODO
    MESO_BAG_MESSAGE(0xD2), //TODO
    UPDATE_QUEST_INFO(0xD3), //TODO
    PLAYER_HINT(0xD6), //TODO
    KOREAN_EVENT(0xDB), //TODO
    OPEN_UI(0xDC), //TODO
    LOCK_UI(0xDD), //TODO
    DISABLE_UI(0xDE), //TODO
    SPAWN_GUIDE(0xDF), //TODO
    TALK_GUIDE(0xE0), //TODO
    SHOW_COMBO(0xE1), //TODO
    COOLDOWN(0xEA), //TODO
    SPAWN_MONSTER(0xEC), //TODO
    KILL_MONSTER(0xED), //TODO
    SPAWN_MONSTER_CONTROL(0xEE), //TODO
    MOVE_MONSTER(0xEF), //TODO
    MOVE_MONSTER_RESPONSE(0xF0), //TODO
    APPLY_MONSTER_STATUS(0xF2), //TODO
    CANCEL_MONSTER_STATUS(0xF3), //TODO
    RESET_MONSTER_ANIMATION(0xF4),//LOL? o.o TODO we'll figure it out
    //Something with mob, but can't figure out00
    DAMAGE_MONSTER(0xF6), //TODO
    ARIANT_THING(0xF9), //TODO
    SHOW_MONSTER_HP(0xFA), //TODO
    CATCH_MONSTER(0xFB), //TODO
    CATCH_MONSTER_WITH_ITEM(0xFC), //TODO
    SHOW_MAGNET(0xFD), //TODO
    SPAWN_NPC(0x101), //TODO
    REMOVE_NPC(0x102), //TODO
    SPAWN_NPC_REQUEST_CONTROLLER(0x103), //TODO
    NPC_ACTION(0x104), //TODO
    SPAWN_HIRED_MERCHANT(0x109), //TODO
    DESTROY_HIRED_MERCHANT(0x10A), //TODO
    UPDATE_HIRED_MERCHANT(0x10B), //TODO
    DROP_ITEM_FROM_MAPOBJECT(0x10C), //TODO
    REMOVE_ITEM_FROM_MAP(0x10D), //TODO
    CANNOT_SPAWN_KITE(0x10E), //TODO
    SPAWN_KITE(0x10F), //TODO
    REMOVE_KITE(0x110), //TODO
    SPAWN_MIST(0x111), //TODO
    REMOVE_MIST(0x112), //TODO
    SPAWN_DOOR(0x113), //TODO
    REMOVE_DOOR(0x114), //TODO
    REACTOR_HIT(0x115), //TODO
    REACTOR_SPAWN(0x117), //TODO
    REACTOR_DESTROY(0x118), //TODO
    SNOWBALL_STATE(0x119), //TODO
    HIT_SNOWBALL(0x11A), //TODO
    SNOWBALL_MESSAGE(0x11B), //TODO
    LEFT_KNOCK_BACK(0x11C), //TODO
    COCONUT_HIT(0x11D), //TODO
    COCONUT_SCORE(0x11E), //TODO
    GUILD_BOSS_HEALER_MOVE(0x11F), //TODO
    GUILD_BOSS_PULLEY_STATE_CHANGE(0x120), //TODO
    MONSTER_CARNIVAL_START(0x121), //TODO
    MONSTER_CARNIVAL_OBTAINED_CP(0x122), //TODO
    MONSTER_CARNIVAL_PARTY_CP(0x123), //TODO
    MONSTER_CARNIVAL_SUMMON(0x124), //TODO
    MONSTER_CARNIVAL_MESSAGE(0x125), //TODO
    MONSTER_CARNIVAL_DIED(0x126), //TODO
    MONSTER_CARNIVAL_LEAVE(0x127), //TODO
    
    ARIANT_ARENA_USER_SCORE(0x129), //TODO
    SHEEP_RANCH_INFO(0x12B), //TODO
    SHEEP_RANCH_CLOTHES(0x12C), //TODO
    ARIANT_SCORE(0x12D), //TODO
    HORNTAIL_CAVE(0x12E), //TODO
    ZAKUM_SHRINE(0x12F), //TODO
    NPC_TALK(0x130), //TODO
    OPEN_NPC_SHOP(0x131), //TODO
    CONFIRM_SHOP_TRANSACTION(0x132), //TODO
    ADMIN_SHOP_MESSAGE(0x133),//lame :P //TODO
    ADMIN_SHOP(0x134), //TODO
    STORAGE(0x135), //TODO
    FREDRICK_MESSAGE(0x136), //TODO
    FREDRICK(0x137), //TODO
    RPS_GAME(0x138), //TODO
    MESSENGER(0x139), //TODO
    PLAYER_INTERACTION(0x13A), //TODO
    
    TOURNAMENT(0x13B), //TODO
    TOURNAMENT_MATCH_TABLE(0x13C), //TODO
    TOURNAMENT_SET_PRIZE(0x13D), //TODO
    TOURNAMENT_UEW(0x13E), //TODO
    TOURNAMENT_CHARACTERS(0x13F),//they never coded this :| //TODO
    
    WEDDING_PROGRESS(0x140),//byte step, int groomid, int brideid //TODO
    WEDDING_CEREMONY_END(0x141), //TODO
    
    PARCEL(0x142), //TODO
    
    CHARGE_PARAM_RESULT(0x143), //TODO
    QUERY_CASH_RESULT(0x144), //TODO
    CASHSHOP_OPERATION(0x145), //TODO
    CASHSHOP_GIFT_INFO_RESULT(0x147), //TODO
    CASHSHOP_CHECK_NAME_CHANGE(0x148), //TODO
    CASHSHOP_CHECK_NAME_CHANGE_POSSIBLE_RESULT(0x149), //TODO
    CASHSHOP_REGISTER_NEW_CHARACTER_RESULT(0x14A), //TODO
    CASHSHOP_CHECK_TRANSFER_WORLD_POSSIBLE_RESULT(0x14B), //TODO
    CASHSHOP_GACHAPON_STAMP_RESULT(0x14C), //TODO
    CASHSHOP_CASH_ITEM_GACHAPON_RESULT(0x14D), //TODO
    CASHSHOP_CASH_GACHAPON_OPEN_RESULT(0x14E), //TODO
    
    KEYMAP(0x14F), //TODO
    AUTO_HP_POT(0x150), //TODO
    AUTO_MP_POT(0x151), //TODO
    SEND_TV(0x155), //TODO
    REMOVE_TV(0x156), //TODO
    ENABLE_TV(0x157), //TODO
    MTS_OPERATION2(0x15B), //TODO
    MTS_OPERATION(0x15C), //TODO
    MAPLELIFE_RESULT(0x15D), //TODO
    MAPLELIFE_ERROR(0x15E), //TODO
    VICIOUS_HAMMER(0x162), //TODO
    VEGA_SCROLL(0x166), //TODO
    //new packets and uses
    //v92 new packets
    STARFORCE_SCROLL_EFFECT(0x9200), //TODO: use starforce scroll and return result
    USE_MAGNIFYING_GLASS_RESULT(0x9201), //TODO: use magnifying glass
    USE_POTENTIAL_SCROLL_RESULT(0x9202), //TODO hope you don't lose your item kekw
    USE_MIRACLE_CUBE_RESULT(0x9203), //TODO
    SET_FOLLOW_REQUEST(0x9204), //TODO aka SET_PASSENGER_REQUEST
    FOLLOW_OTHER(0x9205), //TODO
    FOLLOW_REQUEST_FAILED(0x9206), //TODO
    QUICKSLOT_SET(0x9207), //TODO
    EXPEDITION_RESULT(0x9208), //TODO
    //some BEGIN/END STAGE stuff? maybe needed to clear staged maps?
    CUSTOM_PACKET(0x3713) ; //13 37 lol
    private int code = -2;

    private SendOpcode(int code) {
        this.code = code;
    }

    public int getValue() {
        return code;
    }
}
